wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Cumulative_Final.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Results_Nov12r.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Results_May_2012.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/ElecResults.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/ElecResults_0.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/ElecResults_1.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Recount_Results.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Official_Results2010.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/ElecResults2010.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/official_election_results2010.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/RecountResults2010.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Official_Final_Results2009.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/05_19_09_OfficialElectionResults.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/ElecResults2009.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Nov2008results.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Official_Primary_Election_ResultsMay08.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Training_Election_ResultsMar08.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/UNOFNov07.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/UnofNov07Special.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/May 15 2007 Election Results.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Unofficial_Write_In_Results_for_McMinnville_School_District.pdf'
wget -nc 'http://www.co.yamhill.or.us//sites/default/files/Nov 7 2006 Election Results.pdf'
